### ISSUE TITLE
Extension Methods scope

### ISSUE THREAD

**Issue by kubukoz** [LukaJCB/typeclass-proposal#1]
From the proposal:

```scala
object Ops
  def **(this i: Int)(j: Int): Int = Math.pow(i, j)
}

//whenever `Ops` is in scope
2 ** 3 == 8
```

(aside from the missing `{` after `Ops`)

Shouldn't
```//whenever `Ops` is in scope```
be
```//whenever `Ops.**` is in scope```
?

You'd normally do `import com.example.Ops._` to get all extensions from `Ops`, and `import com.example.Ops.**` for a particular extension method. This would also enable importing extensions from classes:

```scala
class FactorOps(factor: Int){
  def scaled(this i: Int): Int = i * factor
}

val ops = new FactorOps(5)
import ops._

println(10.scaled) //50
```

**Comment by LukaJCB** [comment]
Yes that's how I intended it, thanks! Will change

**Comment by kubukoz** [comment]
Is it worth adding a mention of extensions in classes too?
